name: messenger_complete_rebuild
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.3
  random_string: ^2.3.1
  shared_preferences: ^2.0.13
firebase_core:
random_string:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

